/**
 * Output Snapshots — preserves files generated by tools and uploaded by users
 * across the lifetime of a conversation, even if the original files are later
 * moved or deleted by the user.
 *
 * Storage layout:
 *   {appData}/conversations/{convId}/outputs/
 *   ├── manifest.json          (keyed by normalized originalPath)
 *   └── files/{pathHash}/{basename}
 *
 * Two entry points feed snapshots into the same kernel:
 *   1. snapshotToolOutputs() — called from toolExecutor after a tool completes,
 *      reuses extractFileOutputs() to discover paths from any tool kind.
 *   2. snapshotUserUpload() — called from chatStore.addMessage when a user
 *      message contains an image (or future file) attachment.
 *
 * One read entry point feeds the UI:
 *   resolveFileSource() — returns 'available' (live or from snapshot),
 *   'skipped' (manifest knows about it but no usable snapshot), or 'missing'.
 *
 * Architecture contract:
 *   ★ If a future change adds stripForDisk-style behavior to a NEW content type
 *     (e.g. DocumentContent gaining a filePath + stripping of base64), that
 *     change MUST also add a corresponding snapshotUserUpload() call, or the
 *     new content type will silently lose data when originals are deleted. ★
 */

import { exists, mkdir, readTextFile, writeTextFile, remove, stat, copyFile, rename } from '@tauri-apps/plugin-fs';
import { appDataDir, homeDir } from '@tauri-apps/api/path';
import { joinPath, normalizeSeparators, getBaseName } from '@/utils/pathUtils';
import { extractFileOutputs } from '@/utils/workflowExtractor';
import type { ToolCall } from '@/types';
import { createLogger } from '../logging/logger';

const logger = createLogger('outputSnapshots');

// ────────────────────────────────────────────────────────────────────────────
// Constants
// ────────────────────────────────────────────────────────────────────────────

/** Single file size cap. Above this, snapshot is skipped with reason='oversized'. */
const MAX_FILE_BYTES = 5 * 1024 * 1024 * 1024; // 5 GB

/** Manifest schema version */
const MANIFEST_VERSION = 1 as const;

// ────────────────────────────────────────────────────────────────────────────
// Types
// ────────────────────────────────────────────────────────────────────────────

export type SnapshotSource = 'tool-output' | 'user-upload' | 'code-save';

export interface SnapshotEntry {
  /** Normalized absolute path of the original file (manifest index key) */
  originalPath: string;
  /** Filename for display */
  basename: string;
  /** Snapshot location relative to outputs/ ; empty string = not snapshotted */
  snapshotRelPath: string;
  /** Bytes */
  size: number;
  /** Original file mtime when snapshot was taken (ms epoch, 0 if unknown) */
  originalMtime: number;
  /** When the snapshot entry was created (ms epoch) */
  snapshottedAt: number;
  /** Where this entry came from */
  source: SnapshotSource;
  /**
   * Reference back to the producing event:
   *   - tool-output: tool_use_id
   *   - user-upload: messageId
   * Currently unused by P0 UI; reserved for P1 traceability features.
   */
  refId: string;
  /**
   * Reference kind:
   *   - tool-output: tool name (write_file, run_command, ...)
   *   - user-upload: 'image' (or future: 'document', etc.)
   * Currently unused by P0 UI; reserved for P1 traceability features.
   */
  refKind: string;
  /** Reason snapshotRelPath is empty. Only set when not snapshotted. */
  skipReason?: 'oversized' | 'copy-failed';
}

export interface OutputManifest {
  version: typeof MANIFEST_VERSION;
  /** Keyed by normalizedOriginalPath */
  entries: Record<string, SnapshotEntry>;
}

export type ResolvedSource =
  | { status: 'available'; path: string; isFromSnapshot: boolean }
  | { status: 'skipped'; entry: SnapshotEntry }
  | { status: 'missing'; basename: string; originalPath: string };

interface SnapshotMeta {
  source: SnapshotSource;
  refId: string;
  refKind: string;
}

// ────────────────────────────────────────────────────────────────────────────
// Module-level state (caches + locks)
// ────────────────────────────────────────────────────────────────────────────

/**
 * In-memory manifest cache.
 * Critical for performance: without this, every FileAttachment render
 * (potentially 100+ per conversation) would trigger a disk read.
 */
const manifestCache = new Map<string, OutputManifest>();

/**
 * Per-conversation serialization lock.
 * Prevents read-modify-write races when multiple snapshots run concurrently
 * (e.g. user upload + tool output finishing at the same time).
 */
const convLocks = new Map<string, Promise<unknown>>();

/** Cached app data base path */
let cachedAppDataBase: string | null = null;
/** Cached home directory (for ~ expansion) */
let cachedHomeDir: string | null = null;

// ────────────────────────────────────────────────────────────────────────────
// Helpers
// ────────────────────────────────────────────────────────────────────────────

/** Get the outputs/ directory for a specific conversation. Creates if needed. */
async function getOutputsDir(convId: string): Promise<string> {
  if (!cachedAppDataBase) {
    const appData = await appDataDir();
    cachedAppDataBase = joinPath(appData, 'conversations');
  }
  const dir = joinPath(cachedAppDataBase, convId, 'outputs');
  if (!(await exists(dir))) {
    await mkdir(dir, { recursive: true });
  }
  return dir;
}

/** Normalize a path to canonical form (forward slashes, no trailing slash). */
function normalizePath(p: string): string {
  return normalizeSeparators(p).replace(/\/+$/, '');
}

/** Check if a path looks like an absolute filesystem path (Unix or Windows). */
function isAbsolutePath(p: string): boolean {
  return p.startsWith('/') || /^[A-Za-z]:[\\/]/.test(p);
}

/**
 * Expand a leading `~` to the user's home directory.
 * Returns the original path unchanged if no expansion is needed or homeDir() fails.
 * The AI sometimes emits ~/... paths in chat narrative even though they're not real
 * filesystem paths until expanded.
 */
async function expandTilde(p: string): Promise<string> {
  if (!p.startsWith('~/') && p !== '~') return p;
  try {
    if (!cachedHomeDir) {
      cachedHomeDir = await homeDir();
    }
    if (p === '~') return cachedHomeDir;
    return joinPath(cachedHomeDir, p.slice(2));
  } catch {
    return p;
  }
}

/**
 * Stable, non-cryptographic hash of a path string.
 * Uses djb2 + length-mix; outputs 16-char base36 string.
 * Collision probability is negligible at conversation scale (a few hundred files).
 */
function hashPath(p: string): string {
  let h = 5381;
  for (let i = 0; i < p.length; i++) {
    h = ((h << 5) + h + p.charCodeAt(i)) | 0;
  }
  // Mix in length so two paths of different lengths can never collide trivially
  return (Math.abs(h).toString(36) + p.length.toString(36)).slice(0, 16).padEnd(8, '0');
}

/**
 * Run an async function under a per-conversation lock.
 * Operations on the same conversation are serialized; different conversations run in parallel.
 */
async function withConvLock<T>(convId: string, fn: () => Promise<T>): Promise<T> {
  const prev = convLocks.get(convId) ?? Promise.resolve();
  const next = prev.then(fn, fn);
  // Track the next-in-line; .catch ensures one failure doesn't poison the chain.
  convLocks.set(convId, next.catch(() => undefined));
  return next;
}

/** Safe stat — returns null if file doesn't exist or stat fails. */
async function safeStat(path: string) {
  try {
    return await stat(path);
  } catch (e) {
    logger.warn('[snapshot] stat failed (capability or missing file?)', { path, err: String(e) });
    return null;
  }
}

// ────────────────────────────────────────────────────────────────────────────
// Manifest read/write (cached + atomic)
// ────────────────────────────────────────────────────────────────────────────

async function loadManifest(convId: string): Promise<OutputManifest> {
  const cached = manifestCache.get(convId);
  if (cached) return cached;

  const dir = await getOutputsDir(convId);
  const path = joinPath(dir, 'manifest.json');
  let manifest: OutputManifest = { version: MANIFEST_VERSION, entries: {} };

  try {
    if (await exists(path)) {
      const text = await readTextFile(path);
      const parsed = JSON.parse(text) as OutputManifest;
      if (parsed.version === MANIFEST_VERSION && parsed.entries) {
        manifest = parsed;
      }
    }
  } catch (e) {
    logger.warn('manifest load failed, falling back to empty', { convId, err: e });
  }

  manifestCache.set(convId, manifest);
  return manifest;
}

/** Atomic manifest write: write to .tmp, then rename. */
async function saveManifest(convId: string, manifest: OutputManifest): Promise<void> {
  // Update cache immediately so subsequent reads see new state even if disk write is in flight
  manifestCache.set(convId, manifest);

  const dir = await getOutputsDir(convId);
  const target = joinPath(dir, 'manifest.json');
  const tmp = `${target}.tmp`;
  const json = JSON.stringify(manifest, null, 2);

  try {
    await writeTextFile(tmp, json);
    // rename is atomic on POSIX; on Windows it requires the target not to exist
    try {
      await remove(target);
    } catch {
      // target may not exist yet
    }
    await rename(tmp, target);
  } catch (e) {
    logger.warn('manifest save failed', { convId, err: e });
    // Cache is already updated; next process restart will reload from disk and lose this update.
    // Acceptable for a fire-and-forget snapshot system.
  }
}

// ────────────────────────────────────────────────────────────────────────────
// Snapshot kernel
// ────────────────────────────────────────────────────────────────────────────

function buildEntry(
  normalized: string,
  size: number,
  mtime: number,
  meta: SnapshotMeta,
  snapshotRelPath: string,
  skipReason?: 'oversized' | 'copy-failed',
): SnapshotEntry {
  return {
    originalPath: normalized,
    basename: getBaseName(normalized),
    snapshotRelPath,
    size,
    originalMtime: mtime,
    snapshottedAt: Date.now(),
    source: meta.source,
    refId: meta.refId,
    refKind: meta.refKind,
    ...(skipReason ? { skipReason } : {}),
  };
}

async function recordEntry(convId: string, entry: SnapshotEntry): Promise<SnapshotEntry> {
  const manifest = await loadManifest(convId);
  manifest.entries[entry.originalPath] = entry;
  await saveManifest(convId, manifest);
  return entry;
}

/**
 * Snapshot a single file. Idempotent: subsequent calls for the same originalPath
 * overwrite the previous snapshot (so edit_file etc. naturally produce "latest version" semantics).
 *
 * Returns the resulting manifest entry, or null if the file should not be snapshotted
 * (path invalid, file gone, target is a directory, etc.).
 */
export async function snapshotFile(
  convId: string,
  rawPath: string,
  meta: SnapshotMeta,
): Promise<SnapshotEntry | null> {
  if (!rawPath) return null;
  // Expand ~/... before normalization — AI tools sometimes pass home-relative paths
  // through their input even when the underlying tool expands them internally.
  const expanded = await expandTilde(rawPath);
  const normalized = normalizePath(expanded);
  if (!isAbsolutePath(normalized)) {
    logger.warn('[snapshot] rejected non-absolute path', { rawPath, normalized });
    return null;
  }

  return withConvLock(convId, async () => {
    const outputsDir = await getOutputsDir(convId);
    // Idempotency guard: don't snapshot files already inside outputs/
    // (prevents recursion when AI writes directly to the session output dir)
    if (normalized.startsWith(outputsDir)) return null;

    const st = await safeStat(normalized);
    if (!st || !st.isFile) return null;

    const mtimeMs = st.mtime ? st.mtime.getTime() : 0;

    // Oversized check
    if (st.size > MAX_FILE_BYTES) {
      logger.info('snapshot skipped: oversized', { convId, path: normalized, size: st.size });
      return await recordEntry(
        convId,
        buildEntry(normalized, st.size, mtimeMs, meta, '', 'oversized'),
      );
    }

    // Copy
    const subdir = joinPath(outputsDir, 'files', hashPath(normalized));
    const basename = getBaseName(normalized);
    const dest = joinPath(subdir, basename);
    try {
      if (!(await exists(subdir))) {
        await mkdir(subdir, { recursive: true });
      }
      await copyFile(normalized, dest);
    } catch (e) {
      logger.warn('snapshot copy failed', { convId, src: normalized, err: e });
      return await recordEntry(
        convId,
        buildEntry(normalized, st.size, mtimeMs, meta, '', 'copy-failed'),
      );
    }

    return await recordEntry(
      convId,
      buildEntry(normalized, st.size, mtimeMs, meta, `files/${hashPath(normalized)}/${basename}`),
    );
  });
}

// ────────────────────────────────────────────────────────────────────────────
// Public capture entry points
// ────────────────────────────────────────────────────────────────────────────

/**
 * Snapshot all output files produced by a single tool call.
 * Reuses extractFileOutputs() to discover paths from any tool kind (write_file,
 * edit_file, run_command stdout/cmd parsing, generate_image, MCP, etc.).
 *
 * Note: extractFileOutputs has a "intermediate script filter" that operates on
 * the FULL toolCalls array (it knows which .py/.js scripts were later executed).
 * When called per-toolCall here, that filter is ineffective — intermediate scripts
 * may also be snapshotted. This is accepted as a minor space cost (KB-level)
 * with no functional impact.
 */
export async function snapshotToolOutputs(
  convId: string,
  toolCall: { id: string; name: string; input: Record<string, unknown>; result: string },
): Promise<void> {
  const outputs = extractFileOutputs([toolCall as ToolCall], { includeReads: false });
  const targets = outputs.filter((o) => o.operation === 'create' || o.operation === 'write');
  if (targets.length === 0) return;

  for (const { path } of targets) {
    await snapshotFile(convId, path, {
      source: 'tool-output',
      refId: toolCall.id,
      refKind: toolCall.name,
    });
  }
}

/**
 * Snapshot a file uploaded by the user (currently only images).
 * Called fire-and-forget from chatStore.addMessage when a user message
 * contains an ImageContent block with a filePath.
 */
export async function snapshotUserUpload(
  convId: string,
  filePath: string,
  messageId: string,
  kind: 'image',
): Promise<void> {
  await snapshotFile(convId, filePath, {
    source: 'user-upload',
    refId: messageId,
    refKind: kind,
  });
}

/**
 * Snapshot a file the user manually saved from a markdown code block in chat.
 * Called fire-and-forget from MarkdownRenderer.handleSaveAs after a successful
 * write. Without this, code-block-saved files are at the mercy of the user's
 * file management — exactly the case the snapshot system is meant to protect.
 */
export async function snapshotCodeBlockSave(
  convId: string,
  filePath: string,
  language: string | undefined,
): Promise<void> {
  await snapshotFile(convId, filePath, {
    source: 'code-save',
    refId: '',  // no message context — code blocks don't have a stable id
    refKind: language || 'text',
  });
}

// ────────────────────────────────────────────────────────────────────────────
// Public read entry point
// ────────────────────────────────────────────────────────────────────────────

/**
 * Resolve where to actually load a file from when rendering a card.
 * Priority chain:
 *   1. Live original (when path is absolute and exists)
 *   2. Session outputs/ probe by basename — covers two real cases:
 *      a. AI followed the no-workspace prompt and wrote directly to outputDir,
 *         then the chat narrative mentions only a bare basename.
 *      b. The path was passed through markdown text-extraction and lost its
 *         directory part.
 *   3. Snapshot fallback via manifest
 *   4. skipped (manifest entry exists but no usable copy)
 *   5. missing
 */
export async function resolveFileSource(
  convId: string | undefined,
  originalPath: string,
): Promise<ResolvedSource> {
  const basename = getBaseName(originalPath);

  // 0. Expand `~/...` if present — AI sometimes emits home-relative paths in narrative text.
  const expandedPath = await expandTilde(originalPath);

  // 1. Live original takes priority — even if a snapshot exists, the user's
  //    in-place edits should be reflected.
  if (expandedPath && isAbsolutePath(expandedPath)) {
    if (await exists(expandedPath)) {
      return { status: 'available', path: expandedPath, isFromSnapshot: false };
    }
  }

  // 2. Session outputs/ top-level probe (handles AI-wrote-to-outputDir directly case)
  if (convId && basename) {
    try {
      const outputsDir = await getOutputsDir(convId);
      const candidate = joinPath(outputsDir, basename);
      if (await exists(candidate)) {
        return { status: 'available', path: candidate, isFromSnapshot: false };
      }
    } catch {
      // ignore — fall through to manifest lookup
    }
  }

  // 3. Fall back to snapshot via manifest
  if (convId) {
    const manifest = await loadManifest(convId);

    // 3a. Exact path match (the common case — toolCall input.path matches the lookup)
    const exactEntry = manifest.entries[normalizePath(expandedPath)];
    if (exactEntry) {
      if (exactEntry.snapshotRelPath) {
        const dir = await getOutputsDir(convId);
        const full = joinPath(dir, exactEntry.snapshotRelPath);
        if (await exists(full)) {
          return { status: 'available', path: full, isFromSnapshot: true };
        }
      }
      // Manifest knows but no usable snapshot file
      return { status: 'skipped', entry: exactEntry };
    }

    // 3b. Basename match — handles "AI text mentioned bare basename" case where the
    //      lookup path lacks directory info but a manifest entry exists for the same filename.
    if (basename) {
      const basenameMatch = Object.values(manifest.entries).find(
        (e) => e.basename === basename && e.snapshotRelPath,
      );
      if (basenameMatch) {
        const dir = await getOutputsDir(convId);
        const full = joinPath(dir, basenameMatch.snapshotRelPath);
        if (await exists(full)) {
          return { status: 'available', path: full, isFromSnapshot: true };
        }
      }
    }
  }

  // 4. No record at all
  return { status: 'missing', basename, originalPath };
}


// ────────────────────────────────────────────────────────────────────────────
// Cleanup
// ────────────────────────────────────────────────────────────────────────────

/**
 * Clean up all snapshot state for a conversation.
 *
 * Note: deleteConversationFiles() in conversationStorage already rm -rf's the
 * entire conversation directory, which includes outputs/. This function is
 * therefore mostly redundant for the disk side, but it MUST be called to
 * clear the in-memory manifest cache. Otherwise stale entries linger.
 */
export async function cleanupConversationOutputs(convId: string): Promise<void> {
  manifestCache.delete(convId);
  convLocks.delete(convId);

  // Defensive: also try to remove the dir directly, in case the caller didn't
  // also call deleteConversationFiles. swallow errors (already-deleted is fine).
  try {
    if (!cachedAppDataBase) {
      const appData = await appDataDir();
      cachedAppDataBase = joinPath(appData, 'conversations');
    }
    const dir = joinPath(cachedAppDataBase, convId, 'outputs');
    if (await exists(dir)) {
      await remove(dir, { recursive: true });
    }
  } catch {
    // Non-critical
  }
}

// ────────────────────────────────────────────────────────────────────────────
// Test-only exports (do not import from production code)
// ────────────────────────────────────────────────────────────────────────────

/** @internal — exposed for unit tests only */
export const __testing = {
  hashPath,
  normalizePath,
  isAbsolutePath,
  loadManifest,
  saveManifest,
  resetCaches: () => {
    manifestCache.clear();
    convLocks.clear();
    cachedAppDataBase = null;
  },
  MAX_FILE_BYTES,
};
