import { writeFileSync, readFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { ModelCapabilities } from '../src/core/llm/modelCapabilities';
import type { ModelRecord, ModelsDevApi } from '../src/core/llm/model-data/schema';
import { mapModelsDevModel } from '../src/core/llm/model-data/mapModelsDev';
import { mergeLayers } from '../src/core/llm/model-data/merge';

// Conservative per-turn request budget caps, keyed by reasoning protocol.
// outputCeiling carries the true max; this only bounds what we REQUEST so a
// large model max can't (a) collapse usable input context for Claude, or
// (b) be requested wholesale on knob-less models. Escalation climbs to ceiling.
function requestCap(thinking: ModelRecord['thinking']): number {
  if (thinking === 'openai-reasoning') return 128000; // reasoning shares the output budget → needs room
  if (thinking === 'qwen') return 65536;               // qwen thinking_budget territory
  return 32768;                                        // anthropic / uncontrollable / non-reasoning
}
function requestBudget(r: ModelRecord): number {
  return Math.min(r.maxOutputTokens, requestCap(r.thinking));
}

const HERE = dirname(fileURLToPath(import.meta.url));
const DATA = resolve(HERE, '../src/core/llm/model-data');
const OUT = resolve(HERE, '../src/core/llm/generated/modelData.generated.ts');

export function recordsToCapabilities(recs: ModelRecord[]): Record<string, ModelCapabilities> {
  const out: Record<string, ModelCapabilities> = {};
  for (const r of recs) {
    const budget = requestBudget(r);
    out[r.id] = {
      vision: r.vision,
      thinking: r.thinking ?? false,
      toolResultImages: r.toolResultImages ?? 'workaround',
      documentBlock: r.documentBlock ?? false,
      maxOutputTokens: budget,
      outputCeiling: Math.max(r.outputCeiling ?? r.maxOutputTokens, budget),
      contextWindow: r.contextWindow,
    };
  }
  return out;
}

export function recordsToPricing(recs: ModelRecord[]): [string, NonNullable<ModelRecord['pricing']>][] {
  return recs
    .filter((r): r is ModelRecord & { pricing: NonNullable<ModelRecord['pricing']> } => !!r.pricing)
    .map(r => [r.id, r.pricing] as [string, NonNullable<ModelRecord['pricing']>])
    .sort((a, b) => b[0].length - a[0].length);
}

// Serialize a value as TS source using single quotes for strings (so the file
// reads like hand-written TS and matches lint conventions).
function ts(value: unknown, indent = 0): string {
  const pad = '  '.repeat(indent);
  const padIn = '  '.repeat(indent + 1);
  if (value === null) return 'null';
  if (typeof value === 'number' || typeof value === 'boolean') return String(value);
  if (typeof value === 'string') return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
  if (Array.isArray(value)) {
    if (value.length === 0) return '[]';
    const items = value.map(v => padIn + ts(v, indent + 1));
    return `[\n${items.join(',\n')}\n${pad}]`;
  }
  if (typeof value === 'object') {
    const entries = Object.entries(value as Record<string, unknown>);
    if (entries.length === 0) return '{}';
    const items = entries.map(([k, v]) => `${padIn}${quoteKey(k)}: ${ts(v, indent + 1)}`);
    return `{\n${items.join(',\n')}\n${pad}}`;
  }
  return 'undefined';
}

function quoteKey(k: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(k) ? k : `'${k.replace(/'/g, "\\'")}'`;
}

export function buildGeneratedSource(recs: ModelRecord[]): string {
  const caps = recordsToCapabilities(recs);
  const pricing = recordsToPricing(recs);
  return `// ╔════════════════════════════════════════════════════════════════╗
// ║  DO NOT EDIT — generated by scripts/gen-model-data.ts            ║
// ║  Sources: model-data/vendor/models-dev.snapshot.json (re-pull    ║
// ║  with \`npm run sync:models -- --write\`) + model-data/overlay/*.   ║
// ║  Regenerate with \`npm run gen:models\`.                           ║
// ╚════════════════════════════════════════════════════════════════╝
import type { ModelCapabilities } from '../modelCapabilities';

export const GENERATED_KNOWN_MODELS: Record<string, ModelCapabilities> = ${ts(caps)};

export const GENERATED_MODEL_PRICING: [string, { input: number; output: number; cacheRead: number; cacheCreation: number }][] = ${ts(pricing)};
`;
}

export function loadAndMerge(): ModelRecord[] {
  const snapshotPath = resolve(DATA, 'vendor/models-dev.snapshot.json');
  const api: ModelsDevApi = existsSync(snapshotPath) ? JSON.parse(readFileSync(snapshotPath, 'utf8')) : {};
  const snapshot: ModelRecord[] = [];
  for (const [pid, p] of Object.entries(api)) {
    for (const model of Object.values(p.models ?? {})) {
      // Skip image/video-gen models (no text output) and zero-context stubs
      const outputModalities = model.modalities?.output ?? ['text'];
      if (!outputModalities.includes('text')) continue;
      if (!model.limit?.context) continue;
      snapshot.push(mapModelsDevModel(model, pid));
    }
  }
  const volc = JSON.parse(readFileSync(resolve(DATA, 'overlay/volcengine.json'), 'utf8')).models as ModelRecord[];
  const local = JSON.parse(readFileSync(resolve(DATA, 'overlay/local-models.json'), 'utf8')).models as ModelRecord[];
  const overrides = JSON.parse(readFileSync(resolve(DATA, 'overlay/abu-overrides.json'), 'utf8')).overrides as Record<string, Partial<ModelRecord>>;
  return mergeLayers(snapshot, [...volc, ...local], overrides);
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const src = buildGeneratedSource(loadAndMerge());
  mkdirSync(dirname(OUT), { recursive: true });
  const prev = existsSync(OUT) ? readFileSync(OUT, 'utf8') : '';
  if (process.argv.includes('--check')) {
    if (prev.replace(/\r\n/g, '\n') !== src) { console.error('✗ generated model data is stale — run `npm run gen:models`'); process.exit(1); }
    console.log('✓ generated model data is up to date'); process.exit(0);
  }
  writeFileSync(OUT, src);
  console.log(`✓ wrote ${OUT}`);
}
